apiVersion: operator.m3db.io/v1alpha1
kind: M3DBCluster
metadata:
  name: simple-cluster
spec:
  image: quay.io/m3db/m3dbnode:latest
  replicationFactor: 3
  numberOfShards: 256
  imagePullPolicy: IfNotPresent
  etcdEndpoints:
  - http://etcd0:2379
  - http://etcd1:2379
  - http://etcd2:2379
  isolationGroups:
  - name: group1
    numInstances: 1
  - name: group2
    numInstances: 1
  - name: group3
    numInstances: 1
  podIdentityConfig:
    sources:
      - PodUID
  namespaces:
    - name: metrics-10s:2d
      preset: 10s:2d
      