// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"websvc/device/models"
)

// GetDeviceDeviceIDHandlerFunc turns a function with the right signature into a get device device ID handler
type GetDeviceDeviceIDHandlerFunc func(GetDeviceDeviceIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDeviceDeviceIDHandlerFunc) Handle(params GetDeviceDeviceIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetDeviceDeviceIDHandler interface for that can handle valid get device device ID params
type GetDeviceDeviceIDHandler interface {
	Handle(GetDeviceDeviceIDParams, *models.Principal) middleware.Responder
}

// NewGetDeviceDeviceID creates a new http.Handler for the get device device ID operation
func NewGetDeviceDeviceID(ctx *middleware.Context, handler GetDeviceDeviceIDHandler) *GetDeviceDeviceID {
	return &GetDeviceDeviceID{Context: ctx, Handler: handler}
}

/* GetDeviceDeviceID swagger:route GET /device/{deviceId} getDeviceDeviceId

Returns a device by ID.

*/
type GetDeviceDeviceID struct {
	Context *middleware.Context
	Handler GetDeviceDeviceIDHandler
}

func (o *GetDeviceDeviceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDeviceDeviceIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
