// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"websvc/device/models"
)

// GetDeviceDeviceIDOKCode is the HTTP code returned for type GetDeviceDeviceIDOK
const GetDeviceDeviceIDOKCode int = 200

/*GetDeviceDeviceIDOK A Device object.

swagger:response getDeviceDeviceIdOK
*/
type GetDeviceDeviceIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Device `json:"body,omitempty"`
}

// NewGetDeviceDeviceIDOK creates GetDeviceDeviceIDOK with default headers values
func NewGetDeviceDeviceIDOK() *GetDeviceDeviceIDOK {

	return &GetDeviceDeviceIDOK{}
}

// WithPayload adds the payload to the get device device Id o k response
func (o *GetDeviceDeviceIDOK) WithPayload(payload *models.Device) *GetDeviceDeviceIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get device device Id o k response
func (o *GetDeviceDeviceIDOK) SetPayload(payload *models.Device) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDeviceDeviceIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDeviceDeviceIDBadRequestCode is the HTTP code returned for type GetDeviceDeviceIDBadRequest
const GetDeviceDeviceIDBadRequestCode int = 400

/*GetDeviceDeviceIDBadRequest The specified device ID is invalid (e.g. not a number).

swagger:response getDeviceDeviceIdBadRequest
*/
type GetDeviceDeviceIDBadRequest struct {
}

// NewGetDeviceDeviceIDBadRequest creates GetDeviceDeviceIDBadRequest with default headers values
func NewGetDeviceDeviceIDBadRequest() *GetDeviceDeviceIDBadRequest {

	return &GetDeviceDeviceIDBadRequest{}
}

// WriteResponse to the client
func (o *GetDeviceDeviceIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDeviceDeviceIDNotFoundCode is the HTTP code returned for type GetDeviceDeviceIDNotFound
const GetDeviceDeviceIDNotFoundCode int = 404

/*GetDeviceDeviceIDNotFound A device with the specified ID was not found.

swagger:response getDeviceDeviceIdNotFound
*/
type GetDeviceDeviceIDNotFound struct {
}

// NewGetDeviceDeviceIDNotFound creates GetDeviceDeviceIDNotFound with default headers values
func NewGetDeviceDeviceIDNotFound() *GetDeviceDeviceIDNotFound {

	return &GetDeviceDeviceIDNotFound{}
}

// WriteResponse to the client
func (o *GetDeviceDeviceIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*GetDeviceDeviceIDDefault Unexpected error

swagger:response getDeviceDeviceIdDefault
*/
type GetDeviceDeviceIDDefault struct {
	_statusCode int
}

// NewGetDeviceDeviceIDDefault creates GetDeviceDeviceIDDefault with default headers values
func NewGetDeviceDeviceIDDefault(code int) *GetDeviceDeviceIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDeviceDeviceIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get device device ID default response
func (o *GetDeviceDeviceIDDefault) WithStatusCode(code int) *GetDeviceDeviceIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get device device ID default response
func (o *GetDeviceDeviceIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetDeviceDeviceIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
