// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDeviceVersionOKCode is the HTTP code returned for type GetDeviceVersionOK
const GetDeviceVersionOKCode int = 200

/*GetDeviceVersionOK OK

swagger:response getDeviceVersionOK
*/
type GetDeviceVersionOK struct {
}

// NewGetDeviceVersionOK creates GetDeviceVersionOK with default headers values
func NewGetDeviceVersionOK() *GetDeviceVersionOK {

	return &GetDeviceVersionOK{}
}

// WriteResponse to the client
func (o *GetDeviceVersionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
