clusters:
  - namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - 172.18.0.71:2379
                - 172.18.0.72:2379
                - 172.18.0.73:2379
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority
  