// Code generated by go-swagger; DO NOT EDIT.

// Package restapi API service for login
//
//  Retrieve session Info.
//  Schemes:
//    http
//    https
//  Host: localhost:8080
//  BasePath: /api/v1/auth
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
