// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieve session Info.",
    "title": "API service for login",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1/auth",
  "paths": {
    "/login": {
      "post": {
        "security": [
          {
            "basicAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Returns sessionId.",
        "parameters": [
          {
            "type": "string",
            "name": "X-Tenant-Name",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/logout": {
      "post": {
        "summary": "Clear a session.",
        "parameters": [
          {
            "minimum": 1,
            "type": "string",
            "format": "uuid",
            "name": "X-XSRF-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A Device object."
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieve session Info.",
    "title": "API service for login",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1/auth",
  "paths": {
    "/login": {
      "post": {
        "security": [
          {
            "basicAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Returns sessionId.",
        "parameters": [
          {
            "type": "string",
            "name": "X-Tenant-Name",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/logout": {
      "post": {
        "summary": "Clear a session.",
        "parameters": [
          {
            "minimum": 1,
            "type": "string",
            "format": "uuid",
            "name": "X-XSRF-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A Device object."
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  }
}`))
}
