// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTimeseriesVersionOKCode is the HTTP code returned for type GetTimeseriesVersionOK
const GetTimeseriesVersionOKCode int = 200

/*GetTimeseriesVersionOK OK

swagger:response getTimeseriesVersionOK
*/
type GetTimeseriesVersionOK struct {
}

// NewGetTimeseriesVersionOK creates GetTimeseriesVersionOK with default headers values
func NewGetTimeseriesVersionOK() *GetTimeseriesVersionOK {

	return &GetTimeseriesVersionOK{}
}

// WriteResponse to the client
func (o *GetTimeseriesVersionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
