// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetTimeseriesDeviceIDParams creates a new GetTimeseriesDeviceIDParams object
//
// There are no default values defined in the spec.
func NewGetTimeseriesDeviceIDParams() GetTimeseriesDeviceIDParams {

	return GetTimeseriesDeviceIDParams{}
}

// GetTimeseriesDeviceIDParams contains all the bound params for the get timeseries device ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTimeseriesDeviceID
type GetTimeseriesDeviceIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	DeviceID strfmt.UUID
	/*query timeseries data by duration - 1s, 1m, 1h, 1d, 1w, 1M, 1y.
	  Required: true
	  In: query
	*/
	Duration string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTimeseriesDeviceIDParams() beforehand.
func (o *GetTimeseriesDeviceIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rDeviceID, rhkDeviceID, _ := route.Params.GetOK("deviceId")
	if err := o.bindDeviceID(rDeviceID, rhkDeviceID, route.Formats); err != nil {
		res = append(res, err)
	}

	qDuration, qhkDuration, _ := qs.GetOK("duration")
	if err := o.bindDuration(qDuration, qhkDuration, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDeviceID binds and validates parameter DeviceID from path.
func (o *GetTimeseriesDeviceIDParams) bindDeviceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("deviceId", "path", "strfmt.UUID", raw)
	}
	o.DeviceID = *(value.(*strfmt.UUID))

	if err := o.validateDeviceID(formats); err != nil {
		return err
	}

	return nil
}

// validateDeviceID carries on validations for parameter DeviceID
func (o *GetTimeseriesDeviceIDParams) validateDeviceID(formats strfmt.Registry) error {

	if err := validate.FormatOf("deviceId", "path", "uuid", o.DeviceID.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindDuration binds and validates parameter Duration from query.
func (o *GetTimeseriesDeviceIDParams) bindDuration(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("duration", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("duration", "query", raw); err != nil {
		return err
	}
	o.Duration = raw

	return nil
}
