// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTimeseriesDeviceIDOKCode is the HTTP code returned for type GetTimeseriesDeviceIDOK
const GetTimeseriesDeviceIDOKCode int = 200

/*GetTimeseriesDeviceIDOK timeseries data.

swagger:response getTimeseriesDeviceIdOK
*/
type GetTimeseriesDeviceIDOK struct {
}

// NewGetTimeseriesDeviceIDOK creates GetTimeseriesDeviceIDOK with default headers values
func NewGetTimeseriesDeviceIDOK() *GetTimeseriesDeviceIDOK {

	return &GetTimeseriesDeviceIDOK{}
}

// WriteResponse to the client
func (o *GetTimeseriesDeviceIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetTimeseriesDeviceIDBadRequestCode is the HTTP code returned for type GetTimeseriesDeviceIDBadRequest
const GetTimeseriesDeviceIDBadRequestCode int = 400

/*GetTimeseriesDeviceIDBadRequest The specified device ID is invalid (e.g. not a number).

swagger:response getTimeseriesDeviceIdBadRequest
*/
type GetTimeseriesDeviceIDBadRequest struct {
}

// NewGetTimeseriesDeviceIDBadRequest creates GetTimeseriesDeviceIDBadRequest with default headers values
func NewGetTimeseriesDeviceIDBadRequest() *GetTimeseriesDeviceIDBadRequest {

	return &GetTimeseriesDeviceIDBadRequest{}
}

// WriteResponse to the client
func (o *GetTimeseriesDeviceIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetTimeseriesDeviceIDNotFoundCode is the HTTP code returned for type GetTimeseriesDeviceIDNotFound
const GetTimeseriesDeviceIDNotFoundCode int = 404

/*GetTimeseriesDeviceIDNotFound A device with the specified ID was not found.

swagger:response getTimeseriesDeviceIdNotFound
*/
type GetTimeseriesDeviceIDNotFound struct {
}

// NewGetTimeseriesDeviceIDNotFound creates GetTimeseriesDeviceIDNotFound with default headers values
func NewGetTimeseriesDeviceIDNotFound() *GetTimeseriesDeviceIDNotFound {

	return &GetTimeseriesDeviceIDNotFound{}
}

// WriteResponse to the client
func (o *GetTimeseriesDeviceIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*GetTimeseriesDeviceIDDefault Unexpected error

swagger:response getTimeseriesDeviceIdDefault
*/
type GetTimeseriesDeviceIDDefault struct {
	_statusCode int
}

// NewGetTimeseriesDeviceIDDefault creates GetTimeseriesDeviceIDDefault with default headers values
func NewGetTimeseriesDeviceIDDefault(code int) *GetTimeseriesDeviceIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTimeseriesDeviceIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get timeseries device ID default response
func (o *GetTimeseriesDeviceIDDefault) WithStatusCode(code int) *GetTimeseriesDeviceIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get timeseries device ID default response
func (o *GetTimeseriesDeviceIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetTimeseriesDeviceIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
