// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"websvc/timeseries/models"
)

// PutTimeseriesDeviceIDHandlerFunc turns a function with the right signature into a put timeseries device ID handler
type PutTimeseriesDeviceIDHandlerFunc func(PutTimeseriesDeviceIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTimeseriesDeviceIDHandlerFunc) Handle(params PutTimeseriesDeviceIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutTimeseriesDeviceIDHandler interface for that can handle valid put timeseries device ID params
type PutTimeseriesDeviceIDHandler interface {
	Handle(PutTimeseriesDeviceIDParams, *models.Principal) middleware.Responder
}

// NewPutTimeseriesDeviceID creates a new http.Handler for the put timeseries device ID operation
func NewPutTimeseriesDeviceID(ctx *middleware.Context, handler PutTimeseriesDeviceIDHandler) *PutTimeseriesDeviceID {
	return &PutTimeseriesDeviceID{Context: ctx, Handler: handler}
}

/* PutTimeseriesDeviceID swagger:route PUT /timeseries/{deviceId} putTimeseriesDeviceId

push timeseries data from a device by ID.

*/
type PutTimeseriesDeviceID struct {
	Context *middleware.Context
	Handler PutTimeseriesDeviceIDHandler
}

func (o *PutTimeseriesDeviceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutTimeseriesDeviceIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
