kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: kube-system
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: k8s.io/minikube-hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: "/data/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: m3db
  name: m3db
spec:
  selector:
    matchLabels:
      app: m3db
  template:
    metadata:
      labels:
        app: m3db
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: m3db
          image: 'quay.io/m3db/m3dbnode:v1.0.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7201
              name: http-m3db
              protocol: TCP
            - containerPort: 7203
              name: http-m3db1
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/m3db
              name: minikube-pv
      volumes:
        - name: minikube-pv
---
apiVersion: v1
kind: Service
metadata:
  name: m3db
spec:
  ports:
    - port: 7201
      protocol: TCP
      targetPort: http-m3db
  selector:
    app: m3db
  sessionAffinity: None
  type: LoadBalancer