version: '2.2'

services:
  jobmanager:
    image: flink:latest
    container_name: flk-jobmgr
    ports:
      - "8181:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${FLINK_JOBMANAGER_IP}
        parallelism.default: 2     
    networks:
      sr_cluster_network:
        ipv4_address: ${FLINK_JOBMANAGER_IP}

  taskmanager:
    image: flink:latest
    container_name: flk-taskmgr
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${FLINK_JOBMANAGER_IP}
        taskmanager.numberOfTaskSlots: 2 
    networks:
      sr_cluster_network:
        ipv4_address: ${FLINK_TASKMANAGER_IP}

volumes:
    flink:
      driver: local
      driver_opts:
        o: bind
        device: /data/flink

networks:
  sr_cluster_network:
    external: true