// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostLogoutHandlerFunc turns a function with the right signature into a post logout handler
type PostLogoutHandlerFunc func(PostLogoutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostLogoutHandlerFunc) Handle(params PostLogoutParams) middleware.Responder {
	return fn(params)
}

// PostLogoutHandler interface for that can handle valid post logout params
type PostLogoutHandler interface {
	Handle(PostLogoutParams) middleware.Responder
}

// NewPostLogout creates a new http.Handler for the post logout operation
func NewPostLogout(ctx *middleware.Context, handler PostLogoutHandler) *PostLogout {
	return &PostLogout{Context: ctx, Handler: handler}
}

/* PostLogout swagger:route POST /logout postLogout

Clear a session.

*/
type PostLogout struct {
	Context *middleware.Context
	Handler PostLogoutHandler
}

func (o *PostLogout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostLogoutParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
