// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostLoginParams creates a new PostLoginParams object
//
// There are no default values defined in the spec.
func NewPostLoginParams() PostLoginParams {

	return PostLoginParams{}
}

// PostLoginParams contains all the bound params for the post login operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostLogin
type PostLoginParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: header
	*/
	XTenantName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostLoginParams() beforehand.
func (o *PostLoginParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindXTenantName(r.Header[http.CanonicalHeaderKey("X-Tenant-Name")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXTenantName binds and validates parameter XTenantName from header.
func (o *PostLoginParams) bindXTenantName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("X-Tenant-Name", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("X-Tenant-Name", "header", raw); err != nil {
		return err
	}
	o.XTenantName = raw

	return nil
}
