// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostLogoutOKCode is the HTTP code returned for type PostLogoutOK
const PostLogoutOKCode int = 200

/*PostLogoutOK A Device object.

swagger:response postLogoutOK
*/
type PostLogoutOK struct {
}

// NewPostLogoutOK creates PostLogoutOK with default headers values
func NewPostLogoutOK() *PostLogoutOK {

	return &PostLogoutOK{}
}

// WriteResponse to the client
func (o *PostLogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
